### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by Talamantez** [dluxemburg/node-neurosky#4]
Hi! I'm setting up a Mindwave Mobile on Ubuntu. I have paired the headset with the computer. 
When I run the example:

```
node app.js
```

I receive this error:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:742:11)
    at Object.afterConnect [as oncomplete] (net.js:989:19)
```

Any idea where this is slipping up?
Thanks - Robert

**Comment by jussiry** [comment]
I have the same with Mac (though different line numbers - probably because of newer version).

**Comment by jussiry** [comment]
Ups, you need to have ThinkGear Connector installed and running: http://developer.neurosky.com/docs/doku.php?id=thinkgear_connector_tgc
Linux don't seem to be supported..

Couldn't still get any data through, though.
